name: vide-ci

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
      - name: Test
        run: make test
      - name: Static checks
        run: make lint security

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
      - name: Test
        run: make test
      - name: Static checks
        run: make lint security
